# Generated by Django 3.2.3 on 2021-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
