# Generated by Django 3.2.3 on 2021-05-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
