# Generated by Django 3.2.3 on 2021-05-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210521_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='House',
        ),
    ]
