# Generated by Django 3.2.3 on 2021-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210605_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userslug',
        ),
    ]
