# Generated by Django 3.2.3 on 2021-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_userprofile_preferredmaxrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferredage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferredreligion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
