# Generated by Django 3.2.3 on 2021-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_userprofile_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profilephoto/'),
        ),
    ]
