# Generated by Django 3.2.3 on 2021-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_thumbnail_userprofile_profilethumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='HasRoom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
