# Generated by Django 3.2.3 on 2021-06-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_userprofile_hasroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='accommodationtype',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
