# Generated by Django 3.2.3 on 2021-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_house_accommodationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
