# Generated by Django 3.2.3 on 2021-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_userprofile_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pet',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
