# Generated by Django 3.2.3 on 2021-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='HasRoom',
            field=models.CharField(default='Needs A Room', max_length=255, null=True),
        ),
    ]
