# Generated by Django 3.2.3 on 2021-06-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_userprofile_hasroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='slug',
        ),
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
