# Generated by Django 3.2.3 on 2021-06-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_house_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='slug',
        ),
    ]
